# Generated by Django 2.1 on 2019-03-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('york', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppyinfo',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='./static/images'),
        ),
    ]
