# Generated by Django 2.1 on 2019-03-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('york', '0002_puppyinfo_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppyinfo',
            name='profile_image',
            field=models.ImageField(blank=True, default='./static/images/default.jpg', null=True, upload_to='./static/images'),
        ),
    ]
