# Generated by Django 2.1 on 2019-03-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('york', '0009_auto_20190327_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppyinfo',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/images/default.jpg', null=True, upload_to='../static/images'),
        ),
    ]
