# Generated by Django 2.1 on 2019-04-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('york', '0017_auto_20190328_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppyinfo',
            name='profile_image',
            field=models.ImageField(default='static/images/default.jpg', upload_to='static/images'),
        ),
    ]
