# Generated by Django 2.1 on 2019-04-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('york', '0018_auto_20190403_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppyinfo',
            name='age',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
