# Generated by Django 2.1 on 2019-04-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('york', '0020_auto_20190404_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppyinfo',
            name='age',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
